#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "list.h"
#include "virtual_grid.h"

	int position[2];
	int orientation;
list nodes_to_visit;
list stacks[2];
task main()
{
setSensorMode(gyroSensor, modeEV3Gyro_Angle);

	int cities_found;
	int i;
	int grid[GRID_NROWS*GRID_NCOLS];
	int stack_to_push;

	bool exit;
	list_n test_node;


	list *aux;

	/********Initializing structures********/
	position[0] = 0;
	position[1] = 3;
	orientation = SUL;
	for(i=0;i<GRID_NROWS*GRID_NCOLS;i++)
		grid[i] = -1;
	cities_found = 0;
	set_grid(grid,2,3,-1); // GOAL
	set_grid(grid,position[0],position[1],1);
	initialize_list(nodes_to_visit, QEUE);
	exit = false;
	stack_to_push = 0;
	aux = &stacks[0];
	initialize_list(aux, STACK);
	aux = &stacks[1];
	initialize_list(aux, STACK);
	/***************************************/

	while (cities_found < 4 && !exit){
		 //if(check_objective()){
			cities_found++;
		 //}
		check_surroundings(grid, position, orientation, nodes_to_visit);
		if(!move_to_next_node(grid,position, &orientation, nodes_to_visit, stacks, &stack_to_push))
			exit = true;
		set_grid(grid,position[0],position[1],1);
		if (cities_found == -1)
			check_surroundings(grid, position, orientation, nodes_to_visit);
	}
	print_grid(grid);
	return;
}
